In [6]:
import numpy as np
import time

# import pyximport
# pyximport.install(reload_support=True)
# import retina_sample

In [9]:
nan_array = np.array([[54, np.nan, 1.0], [np.nan, 3434, 1.0], [343, np.nan, 1.0], [np.nan, np.nan, 1.0], [np.nan, np.nan, 1.0], [np.nan, 345345, 1.0]])
nan_array_2 = np.array([[8, np.nan, 1.0], [np.nan, np.nan, 1.0], [np.nan, np.nan, 1.0], [np.nan, np.nan, 1.0], [np.nan, np.nan, 1.0], [np.nan, np.nan, 1.0]])


In [10]:
# %timeit  np.where(np.isnan(nan_array), 0, 1.0) 
print(np.where(np.isnan(nan_array), 0, 1.0))

[[1. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 1.]]


In [50]:
nan_array_2[np.unravel_index(np.where(nan_array_2.ravel()==8),nan_array_2.shape)] = 2
print(nan_array_2)

[[ 2. nan  1.]
 [nan nan  1.]
 [nan nan  1.]
 [nan nan  1.]
 [nan nan  1.]
 [nan nan  1.]]
