In [1]:
import numpy as np
import time

sys.path.append('C:\\Users\\Nicholas\\Documents\\University @ Glasgow\\Year 5\\cython_test\\retinavision')
import retinavision
from os.path import dirname, join
datadir = os.path.dirname(os.path.abspath("__file__"))
print(datadir)

c:\Users\Nicholas\Documents\University @ Glasgow\Year 5\cython_test\retinavision_cython


In [20]:
R = retinavision.Retina()
R.loadLoc(join(datadir, "data", "retinas", "ret50k_loc.pkl"))
R.loadCoeff(join(datadir, "data", "retinas", "ret50k_coeff.pkl"))

X = R.coeff
print(type(X))
print(X.ndim)
print(X[0].shape)
print(X[0].dtype)
print(X[0][20000])

<class 'numpy.ndarray'>
2
(50000,)
object
[[0.00025503 0.00076988 0.00166158 0.00256383 0.0028283  0.00223065
  0.00125778 0.00050705 0.00014614]
 [0.00088031 0.00265746 0.00573542 0.00884978 0.00976267 0.0076997
  0.00434158 0.00175021 0.00050443]
 [0.00217244 0.0065581  0.01415392 0.02183957 0.02409241 0.01900139
  0.01071419 0.00431919 0.00124484]
 [0.00383292 0.01157068 0.02497223 0.03853227 0.04250704 0.03352478
  0.0189034  0.00762049 0.00219632]
 [0.0048348  0.01459514 0.03149973 0.04860424 0.05361797 0.04228784
  0.02384457 0.00961241 0.00277041]
 [0.00436011 0.01316215 0.02840699 0.04383213 0.04835359 0.03813589
  0.02150344 0.00866864 0.0024984 ]
 [0.00281115 0.00848622 0.01831524 0.0282605  0.03117569 0.02458788
  0.01386421 0.00558905 0.00161083]
 [0.00129581 0.00391174 0.00844245 0.01302675 0.01437051 0.01133385
  0.00639074 0.00257629 0.00074252]
 [0.00042704 0.00128913 0.00278223 0.004293   0.00473584 0.0037351
  0.00210609 0.00084902 0.0002447 ]]


In [10]:
# %timeit  np.where(np.isnan(nan_array), 0, 1.0) 
print(np.where(np.isnan(nan_array), 0, 1.0))

[[1. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 1.]]


In [50]:
nan_array_2[np.unravel_index(np.where(nan_array_2.ravel()==8),nan_array_2.shape)] = 2
print(nan_array_2)

[[ 2. nan  1.]
 [nan nan  1.]
 [nan nan  1.]
 [nan nan  1.]
 [nan nan  1.]
 [nan nan  1.]]
